{
    "HumanSytems" [
        {
            "question":"What are the three Disaccahrides?",
            "possibleAns":"",
            "picture":"",
            "questionType":"written",
        },
        {
            "question":"",
            "possibleAns":"",
            "picture":"",
            "questionType":"",
        },
        {
            "question":"",
            "possibleAns":"",
            "picture":"",
            "questionType":"",
        },
        {
            "question":"",
            "possibleAns":"",
            "picture":"",
            "questionType":"",
        },
        {
            "question":"",
            "possibleAns":"",
            "picture":"",
            "questionType":"",
        },
        {
            "question":"",
            "possibleAns":"",
            "picture":"",
            "questionType":"",
        },
        {
            "question":"",
            "possibleAns":"",
            "picture":"",
            "questionType":"",
        },
        {
            "question":"",
            "possibleAns":"",
            "picture":"",
            "questionType":"",
        },
        {
            "question":"",
            "possibleAns":"",
            "picture":"",
            "questionType":"",
        }
    ]
}